import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Disco de Freno Delantero 320mm",
    category: "Discos de freno",
    brand: "Yamaha",
    viscosity: null,
    price: 185000,
    available: true,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/768783-1200-auto?v=639101313486770000&width=1200&height=auto&aspect=true",
    description: "Disco de freno delantero de alto rendimiento para motos Yamaha. Fabricado en acero inoxidable con tratamiento anticorrosión.",
    characteristics: ["Diámetro: 320mm", "Espesor: 5mm", "Material: Acero inoxidable 420", "Perforaciones ventiladas", "Compatible: YZF-R3, MT-03"],
    sku: "YMH-DFD-320",
  },
  {
    id: 2,
    name: "Kit Clutch Completo",
    category: "Partes de clutch",
    brand: "Honda",
    viscosity: null,
    price: 320000,
    available: true,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/772757-1200-auto?v=639101358009000000&width=1200&height=auto&aspect=true",
    description: "Kit completo de clutch para motos Honda. Incluye discos de fricción, discos metálicos y resortes.",
    characteristics: ["Incluye 6 discos de fricción", "Incluye 5 discos metálicos", "Incluye 6 resortes", "Compatible: CBR600, CB500"],
    sku: "HND-KCT-001",
  },
  {
    id: 3,
    name: "Aceite Motor 15W40 Mineral",
    category: "Lubricantes",
    brand: "AKT",
    viscosity: "15W40",
    price: 45000,
    available: true,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/769018-1200-auto?v=639101316742800000&width=1200&height=auto&aspect=true",
    description: "Aceite mineral para motor de 4 tiempos. Formulado especialmente para motos de uso urbano.",
    characteristics: ["Viscosidad: 15W40", "Base mineral", "API: SL/CF", "JASO: MA2", "Contenido: 1 litro"],
    sku: "AKT-ACT-15W40",
  },
  {
    id: 4,
    name: "Switch de Encendido Universal",
    category: "Switch de encendido",
    brand: "Suzuki",
    viscosity: null,
    price: 78000,
    available: false,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/771425-1200-auto?v=639101343594930000&width=1200&height=auto&aspect=true",
    description: "Switch de encendido universal con llave. Resistente al agua y a vibraciones.",
    characteristics: ["3 posiciones: OFF/ON/ACC", "Resistente al agua IP65", "Material: Aleación de zinc", "Incluye 2 llaves"],
    sku: "SUZ-SWE-UNI",
  },
  {
    id: 5,
    name: "Aceite Transmisión 80W90",
    category: "Lubricantes",
    brand: "Yamaha",
    viscosity: "80W90",
    price: 38000,
    available: true,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/769082-1200-auto?v=639101317984900000&width=1200&height=auto&aspect=true",
    description: "Aceite para caja de transmisión y diferencial. Protección extrema para engranajes.",
    characteristics: ["Viscosidad: 80W90", "API: GL-5", "Base mineral", "Contenido: 500ml"],
    sku: "YMH-ATR-80W90",
  },
  {
    id: 6,
    name: "Pastillas de Freno Traseras",
    category: "Discos de freno",
    brand: "Honda",
    viscosity: null,
    price: 62000,
    available: true,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/769936-1200-auto?v=639101326557700000&width=1200&height=auto&aspect=true",
    description: "Pastillas de freno traseras de material semi-metálico para frenos de disco.",
    characteristics: ["Material: Semi-metálico", "Incluye 2 pastillas", "Con sensores de desgaste", "Compatible: CB150, CB190"],
    sku: "HND-PFT-002",
  },
  {
    id: 7,
    name: "Palanca Clutch Ajustable",
    category: "Partes de clutch",
    brand: "AKT",
    viscosity: null,
    price: 52000,
    available: true,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/769953-1200-auto?v=639101326669430000&width=1200&height=auto&aspect=true",
    description: "Palanca de clutch ajustable con 6 posiciones. Fabricada en aluminio anodizado CNC.",
    characteristics: ["6 posiciones de ajuste", "Aluminio CNC anodizado", "Plegable en impacto", "Universal 22mm"],
    sku: "AKT-PCL-ADJ",
  },
  {
    id: 8,
    name: "Aceite Motor 20W50 Semi-Sintético",
    category: "Lubricantes",
    brand: "Suzuki",
    viscosity: "20W50",
    price: 68000,
    available: false,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/769042-1200-auto?v=639101316892700000&width=1200&height=auto&aspect=true",
    description: "Aceite semi-sintético de alto rendimiento. Ideal para climas cálidos y motores de alta cilindrada.",
    characteristics: ["Viscosidad: 20W50", "Base semi-sintética", "API: SN/CF", "JASO: MA2", "Contenido: 1 litro"],
    sku: "SUZ-ACT-20W50",
  },
  {
    id: 9,
    name: "Caja Cambios Completa",
    category: "Motor",
    brand: "AKT",
    viscosity: null,
    price: 221975,
    available: false,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/769608-1200-auto?v=639101322617670000&width=1200&height=auto&aspect=true",
    description: "Caja Cambios Completa Akt 180 Ttr-180 Ttx-Cr5 Genui Set.",
    characteristics: ["Caja Cambios: Semi-completa y Completa", "Base semi-sintética", "API: SN/CF", "JASO: MA2", "Contenido: 1 litro"],
    sku: "GB3008",
  },
  {
    id: 10,
    name: "Kit de Arrastre 15X43",
    category: "Transmision",
    brand: "Todas",
    viscosity: null,
    price: 36255,
    available: true,
    image: "https://motorepuestos.vtexassets.com/arquivos/ids/768019-1200-auto?v=639101216158070000&width=1200&height=auto&aspect=true",
    description: "Kit de Arrastre 15X43 (428h-140) Pulsar 135, 150-160 NS, Discover 125-150 ST Revo Spider KitX3",
    characteristics: ["Duracion: +20k Km", "Base semi-sintética", "API: SN/CF", "JASO: MA2", "Contenido: 1 litro"],
    sku: "YT0047",
  },
];

export const CATEGORIES = ["Todos", "Discos de freno", "Partes de clutch", "Lubricantes", "Switch de encendido", "Transmision", "Motor"];
export const BRANDS = ["Todas", "Yamaha", "Honda", "Suzuki", "AKT"];
export const VISCOSITIES = ["Todas", "15W40", "20W50", "80W90"];
export const MAX_PRICE = 400000;

export const formatCOP = (n: number) =>
  new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(n);
